version: "3.8"

services:
  app:
    image: eclipse-temurin:17-jre
    container_name: sciq-backend
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app.jar
      - ./.env:/app/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sciq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=Asia/Seoul
    env_file:
      - .env
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - db
    restart: always
    networks:
      - sciq-network

  db:
    image: mysql:8.0
    container_name: sciq-mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=sciq
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+09:00'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sciq-network
    restart: always

networks:
  sciq-network:
    driver: bridge

volumes:
  mysql-data: